CREATE TABLE IF NOT EXISTS "Users" (
  "id" UUID PRIMARY KEY,
  "username" VARCHAR(255) NOT NULL,
  "password" VARCHAR(1024) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Rooms" (
  "id" UUID PRIMARY KEY,
  "userId" UUID NOT NULL REFERENCES "Users"("id"),
  "title" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
