services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - wschat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - wschat

volumes:
  db:
    driver: local

networks:
  wschat:
    driver: bridge

