services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
